title: "Evies Blog"
description: "This is my personal blog. It riffs on themes such as advanced technology problems (DevOps/Linux/Cloud), how hard it is to be a good human being, the joy of music, why the world feels so absolutely chaotic, and why we should all love each other anyways."
theme: jekyll-theme-minimal
url: "https://kingparra.github.io"
baseurl: "/blog"
